# Will of Act - Local Development Configuration

spring:
  # Database Configuration for Local Development
  datasource:
    url: jdbc:postgresql://localhost:6666/woa_db
    username: woa_user
    password: woa_password
    driver-class-name: org.postgresql.Driver
    hikari:
      # Connection Pool Settings
      connection-timeout: 20000 # 20 seconds
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000 # 5 minutes
      max-lifetime: 1200000 # 20 minutes
  
  # JPA and Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update # Automatically create tables on startup and drop on shutdown
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
