

spring:
  application:
    name: will-of-act
  
  # Flyway Configuration (default for all profiles)
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
  
server:
  port: 8081
